version: '3.6'
services:
  telegraf:
    container_name: telegraf
    image: telegraf
    restart: always
    volumes:
    - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    links:
      - influxdb
    networks:
      - local

  influxdb:
    container_name: influxdb
    image: influxdb:1.8-alpine
    restart: always
    environment:
      - INFLUXDB_DB=influx
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    ports:
      - '8086:8086'
    networks:
      - local
    volumes:
      - influxdb_data:/var/lib/influxdb

  grafana:
    container_name: grafana-server
    image: grafana/grafana
    restart: always
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=
    links:
      - influxdb
    ports:
      - '3000:3000'
    networks:
      - local
    volumes:
      - grafana_data:/var/lib/grafana
      
networks:
  local:

volumes:
  grafana_data: {}
  influxdb_data: {}
